### ISSUE TITLE
Support _ in numeric values

### ISSUE THREAD

**Issue by chuacw** [pontem-network/intellij-move#107]
This isn't recognized by the Move plugin

`        let some_var_name = 1_0000_0000;`

The plugin needs to recognize _ in numeric values

**Comment by chuacw** [comment]
When will this be published into a release?

**Comment by mkurnikov** [comment]
I'm planning to publish it today, it could take another day for Jetbrains
to accept it into the Marketplace. You can expect it tomorrow at some
point.

Best regards,
Maxim Kurnikov.

**Comment by chuacw** [comment]
Thank you for your quick response! Once this is published and verified, I'll go ahead and close this.

**Comment by chuacw** [comment]
Thank you, verified!
