### ISSUE TITLE
"Module is declared with a different address `aptos_framework`" but move compiler doesn't report this

### ISSUE THREAD

**Issue by chuacw** [pontem-network/intellij-move#118]
The plugin is reporting "Module is declared with a different address", but the move compiler doesn't report this, so the plugin has some issue regarding this.

Use attached project to reproduce this issue.
Steps.
1. aptos move clean --assume-yes
2. aptos move compile (with or without --skip-fetch-latest-git-deps makes no difference)

No "Module is declared with a different address" messages are reported by the aptos move compiler.
But if you open the project in IntelliJ, it reports 3 instances of this error message.

See screenshots.

![image](https://github.com/pontem-network/intellij-move/assets/1757930/369a89a4-dbd7-46ba-9c48-36410c44d340)

Here's my aptos info:
![image](https://github.com/pontem-network/intellij-move/assets/1757930/87777b8c-d673-4328-adf1-376136dd384e)

Here's the project:
[a-devs-best-friend.zip](https://github.com/pontem-network/intellij-move/files/12385765/a-devs-best-friend.zip)

Here's a screenshot of compiling the project:
![image](https://github.com/pontem-network/intellij-move/assets/1757930/3b5ee1b1-fae8-4418-8711-494b3b664e4c)

and you can see there's no "Module is declared with a different address" messages.

**Comment by mkurnikov** [comment]
I'll disable it for now.

**Comment by chuacw** [comment]
Thanks, Maksim!
