### ISSUE TITLE
Doesn't show up in `Rust Rover` plugin marketplace

### ISSUE THREAD

**Issue by CapCap** [pontem-network/intellij-move#122]

**Comment by mkurnikov** [comment]
As far as I can tell, `Rust Rover` IDE based on EAP 2023.3 version of the Jetbrains platform. When it hits stable, we're going to deploy a compatible plugin, and after that it should be available in the Marketplace.

**Comment by machinemuse0** [comment]
My CLion 2023.3 version doesn’t work either. Is there any upgrade plan? @mkurnikov

**Comment by mkurnikov** [comment]
Give me three days.

**Comment by CapCap** [comment]
Hi @mkurnikov what is the progress here? 2023.3 is stable.

**Comment by mkurnikov** [comment]
It should be available since today, both for CLion and Rust Rover, please check.

**Comment by junkil-park** [comment]
I also checked RustRover, and it works great! Thank you!

**Comment by mkurnikov** [comment]
I'm going to close it. It should be noted that if/when RustRover base IDE version will be bumped to 2024.1 EAP, it's going to break again. 
I'll try to push the fix for it when it happens.
