### ISSUE TITLE
Linter that can be used in CI

### ISSUE THREAD

**Issue by Ao-senXiong** [pontem-network/intellij-move#134]
Thanks for this great tool. Is there any linter for format and code clean that can be used in CI that will fail the build process if the code is not format right?

**Comment by mkurnikov** [comment]
Hi, you can use Qodana for that. https://www.jetbrains.com/qodana/
  
I made an example repo here 
https://github.com/mkurnikov/qodana-move

**Comment by Ao-senXiong** [comment]
Hi @mkurniko, thanks! Do they also have formatter for move? Like command line tool that automatically format the code to the desired format

**Comment by mkurnikov** [comment]
There's a way to run the formatter from the plugin as a CLI application
https://www.jetbrains.com/help/idea/command-line-formatter.html
You'd also need to install Intellij-Move plugin either manually from the IDE, or from the CLI, see https://www.jetbrains.com/help/idea/install-plugins-from-the-command-line.html

It has a nasty limitation that it can't be executed if you have an IDE instance running already, so, i.e/ CLI pre-commit hooks doesn't really work how they're supposed to.

**Comment by Ao-senXiong** [comment]
Hi @mkurnikov, thanks for sharing so much. I hope there is something more general work regards the IDE. Looks Qodana only does the checks but does not have the option to enforce the code style.

**Comment by mkurnikov** [comment]
Could you expand on "enforcing the code style", what do you mean by that?

**Comment by mkurnikov** [comment]
As there is an official linter and formatter available from the Aptos, I'm closing this.
