### ISSUE TITLE
Incompatible with Build 241

### ISSUE THREAD

**Issue by codenix-sv** [pontem-network/intellij-move#136]
The Move Language plugin is not compatible with the latest build.

> Plugin 'Move Language' (version '1.35.0.233') is not compatible with the current version of the IDE, because it requires build 233.* or older but the current build is PS-241.14494.237

**Comment by mkurnikov** [comment]
On it, thanks for the report.

**Comment by mkurnikov** [comment]
Published the 241 version, it's going to be available tomorrow.

**Comment by codenix-sv** [comment]
> Published the 241 version, it's going to be available tomorrow.
thanks a lot
