### ISSUE TITLE
Support Move 2024

### ISSUE THREAD

**Issue by hokage229** [pontem-network/intellij-move#139]
support of move 2024 for sui
https://marketplace.visualstudio.com/items?itemName=mysten.move

**Comment by mkurnikov** [comment]
There are plans to support new Move features. 
We're starting with Aptos support, implementing new things from https://medium.com/aptoslabs/the-future-of-move-at-aptos-17d0656dcc31 
and then repurpose those for Sui, if features are similar enough. 
Looks like Sui method syntax, macros and enums could eventually be supported.

**Comment by mkurnikov** [comment]
Sui support is going to be dropped in the next stable release.

**Comment by robertdewilde-dev** [comment]
> Sui support is going to be dropped in the next stable release.

Why? 😭 @mkurnikov

**Comment by mkurnikov** [comment]
From now on, the plugin only focuses on the Aptos version of Move Language.

And Sui Move dialect diverged too much from it, it's become nearly impossible to support both in one codebase.
