### ISSUE TITLE
No support of functional-test code format

### ISSUE THREAD

**Issue by welbon** [pontem-network/intellij-move#20]
Hey there. first of all thanks to the author for the perfect plugin. A little suggestion is that to support functional-test code format. It's looks like this now

```move
address alice = {{alice}};
address bob = {{bob}};
script {
use alice::YieldFarmingWarpper;
use 0x1::Debug;

/// 3. Cindy harvest after 20 seconds, checking whether has rewards.
fun init(account: signer) {
let amount00 = YieldFarmingWarpper::query_gov_token_amount( & account);
Debug::print(&amount00);
// assert(amount00 == 0, 10004);
assert(amount00 > 0, 10004);
}
}
```
Thanks again to the author for his dedication and look forward to replying...

**Comment by mkurnikov** [comment]
Hi, thanks for using our plugin! 

> placeholder addresses, like `{{alice}}`, `{{bob}}`

I'm going to add support now for 0.15.0, it seems to be used throughout the Diem codebase a lot.  

> address assignment statements, like `address alice = 0x1;`

Adding support for 0.15.0. Note that Diem drops support for that in Move 1.5. See https://github.com/diem/diem/blob/main/language/changes/5-named-addresses.md#update-for-release-15

Are those features enough for support the use-case, or did I miss something?

**Comment by welbon** [comment]
One more thing, v0.14.x version not have code highlight for variables, and error line track, hope it been adding to new version. Other feature are working well except this issue.

**Comment by mkurnikov** [comment]
> code highlight for variables

Semantic highlighting? 

> error line track

What do you mean?

**Comment by welbon** [comment]
I'm sorry for my poor english.

Code Highlight like this. Eg: the function name is yellow color, and the module name is green color, and so on.
![image](https://user-images.githubusercontent.com/2261238/132041363-5293d96f-c4e7-4dbf-ae69-8bef867dcd8d.png)

Error line track like this, click the file information of error then navigate to target source code.
![image](https://user-images.githubusercontent.com/2261238/132041683-e0ce3e73-40e6-4984-9211-2622ba26f513.png)

**Comment by mkurnikov** [comment]
Got it, thanks for clarification. I'm going to look into both in the next version. Anything else?

By the way, did you try our Dove utility instead of move-cli? It's much better supported. 
See pontem-network/move-tools.

**Comment by welbon** [comment]
One more thing. There still have a problem that not support quick locating to code declaration using shortcut combine such as 'command key + left mouse click' on intellij move plugin 0.16.0. See illustration below
![image](https://user-images.githubusercontent.com/2261238/132817733-bd2b54bd-f125-49bf-9cd2-c1144a542afc.png)

**Comment by mkurnikov** [comment]
For that you'd have to either:
1. Use Dove and Dove.toml manifest to specify dependencies.
2. Wait for an official support for move-cli. We'll add it when they release version supporting their own Move.toml deps manifest.
