### ISSUE TITLE
Errors in code with lambda without params

### ISSUE THREAD

**Issue by i582** [pontem-network/intellij-move#205]
Code:
```move
module BasicCoin::BasicCoin {
    #[test]
    fun test_some() {
        while_loop_with_lambda_break(10)
    }

     fun while_loop_with_lambda_break(s: u64) {
        let spined = &mut s;
        brk2(|| {
            *spined = 10
        });
        *spined = *spined + 1;
    }

    inline fun brk2(f: ||) {
        f();
    }
}
```

<img width="504" src="https://github.com/user-attachments/assets/cb102fa8-3fdf-42e4-8a38-8831071a7b1e">

<img width="358" src="https://github.com/user-attachments/assets/286f591a-eb10-4d44-a9fa-260148ae4add">

Test output:
```
INCLUDING DEPENDENCY MoveStdlib
BUILDING BasicCoin
Running Move unit tests
[ PASS    ] 0xbc::BasicCoin::test_some
Test result: OK. Total tests: 1; passed: 1; failed: 0
{
  "Result": "Success"
}
```

**Comment by i582** [comment]
@mkurnikov why is non_empty_comma_sep_items used here?

```
LambdaType ::= '|' <<non_empty_comma_sep_items LambdaTypeParam>>? '|' Type? { pin = 1 }
LambdaExpr ::= '|' <<non_empty_comma_sep_items PatBinding>> '|' Expr { pin = 1 }
```

**Comment by mkurnikov** [comment]
Considering that in `LambdaType` it's all optional - it's really needs to be optional here too. Let me fix it.

**Comment by mkurnikov** [comment]
FYI, for now I won't accept PRs for the grammars, `lang` and `cli` packages. Get in touch with me at Telegram if you want to contribute on that code.
