### ISSUE TITLE
Move file in functional-test auto format not working

### ISSUE THREAD

**Issue by welbon** [pontem-network/intellij-move#34]
Plugin Version:1.2.0.213
CLion 2021.3.2

There not indent all lines properly while press key combination `Command + Alt + L`

Appearance: 
![image](https://user-images.githubusercontent.com/2261238/147743692-2acff33a-9bf6-4d06-9535-b07a6b0fb4d7.png)

**Comment by mkurnikov** [comment]
I've removed support for `{{name}}` addresses, which now seems to be a premature decision. I will get it back in the next version. 

[Named address syntax](https://github.com/diem/diem/blob/main/language/changes/5-named-addresses.md) meant to be a replacement for that, if you're on 1.5+ version of Move you can try it
```toml
# Move.toml
[addresses]
Alice = "0x1"
``` 
```
let a = @Alice;
```

**Comment by welbon** [comment]
OK, I'll try it later.
