### ISSUE TITLE
Remember Aptos CLI

### ISSUE THREAD

**Issue by shayansanjideh** [pontem-network/intellij-move#57]
Whenever you have to initialize a new Move project, you need to manually enter the location of the CLI on your machine. Is there a way to permanently remember this location so you don't have to enter it every time?

<img width="912" alt="image" src="https://user-images.githubusercontent.com/94887104/180630740-c52336f2-a550-4251-a834-910f974f456a.png">

**Comment by mkurnikov** [comment]
Sorry for leaving it unanswered for so long. Thanks for your report!

I can try to add two different settings, one is IDE-wide which will be set once for every machine. And the second one is for the project if you want to override the path. 

I'll look at it in the next release, which will be ready 1-2 weeks from now.

**Comment by mkurnikov** [comment]
There's a configuration option in Jetbrains products specifically for this use case, try
`File -> New Projects Setup -> Settings For New Projects`. 
Specify aptos cli path there, and it will be applied to all projects created from now on.
