### ISSUE TITLE
[feature request] support spec files

### ISSUE THREAD

**Issue by junkil-park** [pontem-network/intellij-move#59]
A `.move` file can only contain some specs for Move Prover. For example, see the following link: https://github.com/move-language/move/blob/main/language/extensions/move-table-extension/sources/Table.spec.move

Currently, "intellij-move" does not handle this properly.

**Comment by mkurnikov** [comment]
Do you know if there are any scoping rules specific to this naming? Like, `MODULE_NAME.spec.move` having exclusive access to all items in the `MODULE_NAME.move` file, something like that? Maybe there are some docs?

**Comment by mkurnikov** [comment]
I've added support for those files in 1.18.0, I'm going to release a new version at the beginning of the next week. 

Spec modules scoping is really weird, basically, this code is valid
```move
module 0x1::basket {
    fun main() {
        let _a = string::utf8(b"hello");
    }
}
spec 0x1::basket {
    use std::string;
}
```
and those `spec` modules can be anywhere in the package.

**Comment by wrwg** [comment]
> I've added support for those files in 1.18.0, I'm going to release a new version at the beginning of the next week.
> 
> Spec modules scoping is really weird, basically, this code is valid
> 
> ```move
> module 0x1::basket {
>     fun main() {
>         let _a = string::utf8(b"hello");
>     }
> }
> spec 0x1::basket {
>     use std::string;
> }
> ```
> 
> and those `spec` modules can be anywhere in the package.

The scoping was designed like so that if something is only used in the specification, it wouldn't be included in the final dependencies of the module bytecode.

Thanks for making this happen! I guess you are using the Move compilers expansion phase to also deal with spec name resolution? After expansion, the Move compiler and the Spec compiler go very different ways.

**Comment by mkurnikov** [comment]
@wrwg 

> The scoping was designed like so that if something is only used in the specification, it wouldn't be included in the final dependencies of the module bytecode.

Yes, this is what I assumed, I expected the "spec" scope to be nested to the "main" scope, like
```move
module 0x1::main {
   spec 0x1::main {
       use 0x1::string;  // isn't visible outside the scope
   }
}
```
but implicitly. And `schema`, `spec fun` imports will be special cased to be importable from the module itself, to be able to use
```move
use 0x1::main::MySchema;
```

Actually there are `spec module {}` blocks possible inside the modules right now, which behave exactly like that. They expose `spec fun` and `spec schema` items, but AFAIK doesn't expose imports. 

> Thanks for making this happen! I guess you are using the Move compilers expansion phase to also deal with spec name resolution? After expansion, the Move compiler and the Spec compiler go very different ways.

If you mean the Move compiler itself: 
no, I don't use it, Intellij-Move basically reimplements the compiler in Kotlin. I have a scoping rule, which splits spec items and non-spec items into separate groups.
