### ISSUE TITLE
Move compilation failed

### ISSUE THREAD

**Issue by dejavukong** [pontem-network/intellij-move#64]
I am following the [pontem move docs](https://docs.pontem.network/03.-tutorials/aptos-tutorial), got this error when compiling:
```bash
  "Error": "Move compilation failed: Unable to resolve packages for package 'Hello': While resolving dependency 'AptosFramework' in package 'Hello': While processing dependency 'AptosFramework': Unable to find package manifest for 'AptosFramework' at \"/Users/dejavukong/.move/https___github_com_aptos-labs_aptos-core_git_devnet/aptos-move/framework/aptos-framework\""
```

**Comment by mkurnikov** [comment]
Could you check the directory mentioned in the error, and see whether it has a `Move.toml` file inside or not? 

By the way, I don't think it's related to IDE in any way.

**Comment by dejavukong** [comment]
problem solved. the first-time `aptos move compile` may take several minutes, if I terminated this process and re-compile it, may encounter this error.
