### ISSUE TITLE
vector literal are incorrectly flagged

### ISSUE THREAD

**Issue by kingaptos** [pontem-network/intellij-move#69]
According to the [vector literal docs](https://move-language.github.io/move/vector.html#literals), the code below should be correct and the compiler can actually compile it, but the move plugin complains incorrectly with the error described in the comments. 

```rust
module Scratchpad::blank {
 use std::debug;
 use std::vector;

 #[test]
 public entry fun testit() {
  // Compiles correctly, but plugin gives out the error below:
  // ';', '=', '[' or '{' expected, got '['
  // <expression>, BECH32_ADDRESS, DIEM_ADDRESS, IDENTIFIER, INTEGER_LITERAL, PLACEHOLDER_ADDRESS or POLKADOT_ADDRESS expected, got '0'
  let foo = vector<u8>[0u8,1u8,2u8,3u8];
  debug::print<vector<u8>>(&foo);
 }
}
```

Using `Aptos 0.3.2`, on `IntelliJ IDEA 2022.2.1 (Ultimate Edition), Build #IU-222.3739.54, built on August 15, 2022`. 

```
aptos --version
aptos 0.3.2
```

**Comment by mkurnikov** [comment]
Which version of the language plugin is it? Could you update the plugin to the latest one (1.19.0) and check whether the error is still there? I've added support for vector literals in it.
