### ISSUE TITLE
Bug: Unresolved reference

### ISSUE THREAD

**Issue by magj2006** [pontem-network/intellij-move#70]
I already defined friend xx::B in module xx::A, but there is an error which shows  "Unresolved reference" when I call friend fun from A in B.

<img width="348" alt="截屏2022-09-07 11 05 29" src="https://user-images.githubusercontent.com/8394789/188779696-6af78e6c-4087-47b1-8ea7-6491efe3c7b9.png">

<img width="485" alt="截屏2022-09-07 11 05 21" src="https://user-images.githubusercontent.com/8394789/188779691-0f8e6b19-d235-4da5-9047-595f5ebae7aa.png">

Version of Editor and Move language Plugin :
<img width="304" alt="截屏2022-09-07 11 07 23" src="https://user-images.githubusercontent.com/8394789/188779929-81e3103b-6089-448c-b8a9-7a4c8b4b422a.png">

<img width="253" alt="截屏2022-09-07 11 09 03" src="https://user-images.githubusercontent.com/8394789/188780185-a59e785c-77e5-4b8c-a79d-fdf6e1148230.png">

Aptos Cli info:
<img width="627" alt="截屏2022-09-07 11 08 31" src="https://user-images.githubusercontent.com/8394789/188780002-9463edb8-af53-42e0-b5f1-813c7d682efa.png">

**Comment by mkurnikov** [comment]
Thanks for the report! 

I'm sorry but I can't reproduce it, could you:
1. update to the latest version of the plugin, `1.19.0`, and see whether an error persists? 
2. do you have any other "unresolved reference" errors around? If so, you can have an overall problem with resolution, it's fixable with internal refresh (refresh button in Menu Window from here https://github.com/pontem-network/intellij-move/blob/master/changelog/1.17.0.md#new-features)
3. could you make a minimal Move project with a problem?

**Comment by magj2006** [comment]
Hey， I updated it to new version, but it still shew this error. and I refreshed it, no effective. 

<img width="263" alt="截屏2022-09-07 19 58 01" src="https://user-images.githubusercontent.com/8394789/188872919-b64e45b8-74ba-4704-9ff2-e34de6f6035f.png">


<img width="770" alt="截屏2022-09-07 19 57 36" src="https://user-images.githubusercontent.com/8394789/188872835-e7bd98fe-dcce-49e3-95bf-ad11257a63c4.png">

**Comment by mkurnikov** [comment]
Only thing I managed to find is: if your public friend function declaration has space after the `public` keyword like that:
```
    public (friend) fun call_a() {
        print(&b"123");
    }
```
or if this modifier in any other way differs from `public(friend)` (no spaces anywhere), then this error appears. The compiler seems to be fine with any number of spaces between keywords. 

It's a bug, I will fix in the next release.

**Comment by magj2006** [comment]
> 

Thank you.
