### ISSUE TITLE
[Feature Request] Support for separate code/specification units

### ISSUE THREAD

**Issue by wrwg** [pontem-network/intellij-move#73]
The Move language supports since a while to factor out specifications into separate compilation units. If there is a `module M { ... }`, one can create a `spec M { ... }` which contains specifications for the members of `M`. This unit can (and is intended to) be stored in a separate file. Examples are e.g. in the [Aptos Framework](https://github.com/aptos-labs/aptos-core/tree/main/aptos-move/framework/aptos-framework/sources), which has e.g. files like `block.move` and `block.spec.move`.

It would be great if `intellij-move` could support this. The semantics of this features is roughly as follows:

- If there is a `spec M` there must be a matching `module M` (spec units cannot exist by themselves). `spec M` then inherits the scope of `module M`
- `spec M` can then contain specification blocks just as they would be in `module M`.
- in addition, specification blocks have been extended to allow to redeclare the signature of a function for better readability when those blocks are put into different files (those should be tolerated but can otherwise by ignored by the plugin):

```
module M {
  fun f(x: u64): u64 { ...}
}

spec M {
  spec f(x: u64): u64 {
    requires x > 0;
  }
}  
```

**Comment by mkurnikov** [comment]
Thank you for the report, and detailed description of the features!

FYI, the plugin has some support for those since https://pontem.network/intellij-move-whats-new/1-18-0. 

Except for this part

> in addition, specification blocks have been extended to allow to redeclare the signature of a function for better readability when those blocks are put into different files (those should be tolerated but can otherwise be ignored by the plugin):

I'm going to add this one in the next release.

**Comment by mkurnikov** [comment]
@wrwg @junkil-park I've released a new version of the plugin, with this and lots of other fixes.

In this version, I used Aptos packages as a test suite, so the plugin should be ready to develop the standard library with. It would be great if you could tell other Aptos devs to give it a try too, the experience should be much better than before.
