### ISSUE TITLE
Move coding style enhancement

### ISSUE THREAD

**Issue by welbon** [pontem-network/intellij-move#74]
You can add some Move code style enhancements, such as word wrapping when the parameter list of a function declaration too long and function calling that exceeds the right-hand bound, etc.

<img width="886" alt="image" src="https://user-images.githubusercontent.com/2261238/192185773-ac18f892-670e-41c3-a55b-fc36151c6f11.png">

**Comment by mkurnikov** [comment]
Auto-formatter needs a lot of work, I'll try to spend some time on it in the next release.

**Comment by mkurnikov** [comment]
![Peek 2022-09-29 11-16](https://user-images.githubusercontent.com/2341827/192992704-928fef98-a6c9-4618-96c2-1945457fce80.gif)
For this specific use case, there's a context action to split items into separate lines. It's available in all list-like constructs, struct literal params, function params, call arguments, etc.

**Comment by ValentineReese** [comment]
It looks good! Maybe better is that doing this in a auto-format operation

**Comment by welbon** [comment]
It looks good! Maybe better is that doing this in a auto-format operation

**Comment by welbon** [comment]
Another suggestion for improvement arrives --- When the function has too many return values, is it also possible to collapse this line?

<img width="1154" alt="image" src="https://user-images.githubusercontent.com/2261238/204247463-87e81607-5413-46cd-b546-381404a75ea0.png">

**Comment by mkurnikov** [comment]
Fixed long time ago.
