### ISSUE TITLE
no-stop indexing in webstorm

### ISSUE THREAD

**Issue by yekai9527** [pontem-network/intellij-move#77]
once i enable the plugin. webstorm start to scaning and updating again and again 

macbook air m1 with the latest webstorm

**Comment by yekai9527** [comment]
the project  root directory is aptos-core  

if i use some sub directory as project root  for example  aptos-move ,the scanning and indexing stoped

**Comment by mkurnikov** [comment]
Should be fixed in the 1.36.0
