### ISSUE TITLE
Is that possible to make formatter an independent tool??

### ISSUE THREAD

**Issue by yuyang-ok** [pontem-network/intellij-move#88]
Like `rustfmt` or `gofmt`, So we can use it somewhere else.
I think Kotlin can compile to binary without jdk.

**Comment by mkurnikov** [comment]
No, it depends on the platform, which is heavily Java. 

What could be done is to integrate with Github Actions so the proper formatting could be checked in the CI.

**Comment by yuyang-ok** [comment]
@mkurnikov Ok,Thanks.
