### ISSUE TITLE
#[expected_failure breaks syntax highlighting

### ISSUE THREAD

**Issue by movekevin** [pontem-network/intellij-move#89]
When #[expected_failure is included in a unit test, this renders all syntax highlighting in that test invalid. See screenshot below for an example

<img width="1255" alt="Screen Shot 2023-03-02 at 10 42 44 AM" src="https://user-images.githubusercontent.com/105028215/222494734-458d510a-009e-4b65-90d3-90190906a47c.png">

**Comment by mkurnikov** [comment]
Could you check whether you have the latest (1.25.0) version of the plugin?

**Comment by movekevin** [comment]
Ah yes it's fixed in 1.25.0. Thank you!
