### ISSUE TITLE
[Bug] Function calls and dependencies are no longer clickable for local dependencies

### ISSUE THREAD

**Issue by movekevin** [pontem-network/intellij-move#93]
<img width="938" alt="image" src="https://user-images.githubusercontent.com/105028215/222500933-51609b0e-5f3c-4789-8991-49f41e8f9f67.png">

Expected behavior: Clicking bls12381 would take me to the function definition since it's a local dependency.
Version: 1.25.0

**Comment by dkotTech** [comment]
I have the same issue, when try to set up plugin for sui. Looks like there is a bug in the directory encoding.

In the first screenshot unable to find dependencies. 
Look on rev = "framework/testnet" in Move.toml
<img width="1883" alt="image" src="https://github.com/pontem-network/intellij-move/assets/118082692/1a2ceac3-e91b-45c0-9a26-f48cfe22ab90">

When change a rev = "testnet"
Now it works correctly
<img width="2033" alt="image" src="https://github.com/pontem-network/intellij-move/assets/118082692/6f2f0b4e-bb0b-4c00-a1b2-eacb293bbe84">

I use mac os.
IDE: Goland
Plugin version: 1.28.0.231
