### ISSUE TITLE
[bug] Inline functions should not have acquires

### ISSUE THREAD

**Issue by gregnazario** [pontem-network/intellij-move#97]
### Bug

Inline functions aren't required to have acquires, which makes some weird things happen with acquiring generics (to use generic inline functions)

The following example will show that it requires `acquires T`, but the Move compiler will then say it's invalid.
```
inline fun borrow_object<T: key>(source_object: &Object<T>): &T acquires T {
    borrow_global<T>(object::object_address(source_object))
}
```

Instead we should direct users to use the below, and then have the acquires in the function that uses the inline function.
```
inline fun borrow_object<T: key>(source_object: &Object<T>): &T {
    borrow_global<T>(object::object_address(source_object))
}
```

**Comment by mkurnikov** [comment]
Could you clarify please. 
Are `inline` functions' `acquires` invalid for any type, or just for the generic parameters of the function? 
Let's say we have a code like
```
struct S has key {}
inline fun main() acquires S {
    borrow_global<S>(@0x1);
}
```
Is `acquires S` valid in this context, or should it be highlighted as invalid?

**Comment by gregnazario** [comment]
It's a little weird, but I was told that acquires works in inline, but also isn't necessary.

An example where the compiler will fail, but the code won't is this:

```
struct Wrapper<T> has key {}
struct InnerStruct has key {}

fun outer_function() acquires Wrapper<InnerStruct> {
    inner_function<Wrapper<InnerStruct>>();
}

inline fun inner_function<T>(): &Wrapper<T> acquires Wrapper<T> {
    borrow_global<Wrapper<T>>(@0x1);
}
```

In this case, the `acquires Wrapper<T>` will fail compilation on the inline function, because
the compiler doesn't handle it well.

However, the following case will work, as inline functions don't require acquires at all.  Acquires are only applied on the outer function and not the inline function:

```
struct Wrapper<T> has key {}
struct InnerStruct has key {}

fun outer_function() acquires Wrapper<InnerStruct> {
    inner_function<Wrapper<InnerStruct>>();
}

inline fun inner_function<T>(): &Wrapper<T> {
    borrow_global<Wrapper<T>>(@0x1);
}
```

This works for any arbitrary function as well, but also works with acquires:
```
struct S has key {}

fun outer_function() acquires S {
    inner_function();
}

inline fun inner_function(): &S (optional acquires S) {
    borrow_global<S>(@0x1);
}
```

It may be easier just to drop acquires from inline functions for now.
